CM_UNIF = {
    "MNIST":{
        "CC":       177,
        "BATCH":    111,
        "Done":    '',
    },
    "MNIST2":{
        "CC":       125,
        "BATCH":    90,
        "Done":    'rand + pre',
    },
    "FMNIST":{
        "CC":       80,
        "BATCH":    35,
        "Done":    'rand + pre',
    },
    "20NEWS":{
        "CC":       100,
        "BATCH":    600,
        "Comment":  'Best avg',
        "Done":    'rand + pre',
    },
    "20NEWS2":{
        "CC":       11,
        "BATCH":    85,
    },
    "10X73K":{
        "CC":       1000,
        "BATCH":    500,
        "Done":     'rand pre',
    },
    "10X73K2":{
        "CC":       700,
        "BATCH":    32,
    },
    "CIFAR10":{
        "CC":       164,
        "BATCH":    350,
        "Done":    'rand',
    },
    "CIFAR102":{
        "CC":       5,
        "BATCH":    275,
    },
    "R10K":{
        "CC":       10,
        "BATCH":    400,
        "Done":    'rand + pre',
    },
    "USPS":{
        "CC":       40,
        "BATCH":    150,
        "Done":    'rand + pre',
    },
    "PENDIGIT":{
        "CC":       13,
        "BATCH":    80,
        "Done":    'rand + pre',
    },
}

AECM_UNIF = {
    "MNIST":{
        "OUT":      10,
        "BETA":     5,
        "CC":       230,
        "BATCH":    500,
        "LBD":      1.,
        "OPTIM":    'Adam',
        "Done":    'rand + pre',
    },
    "MNIST2":{
        "OUT":      10,
        "BETA":     2,
        "CC":       120,
        "BATCH":    400,
        "LBD":      1.,
        "Comment":  'Previous version',
    },
    "FMNIST2":{
        "OUT":      20,
        "BETA":     .1,
        "CC":       1,
        "BATCH":    32,
        "LBD":      1.,
        "Comment":  'best',
        "Comment":  'BO Running on Springfield',
    },
    "FMNIST":{
        "OUT":      10,
        "BETA":     47,
        "CC":       13,
        "BATCH":    175,
        "LBD":      1.,
        "Comment":  'avg',
    },
    "20NEWS":{
        "OUT":      100,
        "BETA":     232,
        "CC":       10,
        "BATCH":    300,
        "LBD":      1.,
        "Comment":  'Try again',
    },
    "10X73K2":{
        "OUT":      10,
        "BETA":     15,
        "CC":       2000,
        "BATCH":    500,
        "LBD":      1.,
        "OPTIM":    'Adam',
        "Comment":  'from cm',
    },
    "10X73K":{
        "OUT":      10,
        "BETA":     15,
        "CC":       7,
        "BATCH":    40,
        "LBD":      1.,
        "OPTIM":    'Adam',
        "Comment":  'Running an Saving on g1 with cst and decay',
    },
    "CIFAR10":{
        "OUT":      10,
        "BETA":     1,
        "CC":       64,
        "BATCH":    256,
        "LBD":      1.,
        "OPTIM":    'Adam',
        "Done":    'copy cvnet',
    },
    "R10K":{
        "OUT":      75,
        "BETA":     2.3,
        "CC":       1.7,
        "BATCH":    250,
        "LBD":      1.,
        "OPTIM":    'Adam',
        "Done":     'rand + pre',
    },
    "USPS":{
        "OUT":      30,
        "BETA":     0.04,
        "CC":       3.,
        "BATCH":    45,
        "LBD":      1.,
        "OPTIM":    'Adam',
        "Done":    'rand + pre',
    },
    "PENDIGIT":{
        "OUT":      70,
        "BETA":     .5,
        "CC":       13,
        "BATCH":    80,
        "LBD":      1.,
        "OPTIM":    'Adam',
        "Done":    'rand + pre',
    },
}

CvNET_UNIF = {
    "MNIST":{
        "OUT":      40,
        "BETA":     0.2,
        "CC":       15,
        "BATCH":    100,
        "LBD":      1.,
        "COMMENT":    "avg from out",
    },
    "MNISTx":{
        "OUT":      16,
        "BETA":     0.03,
        "CC":       11,
        "BATCH":    150,
        "LBD":      1.,
        "COMMENT":    "best",
    },
    "FMNIST":{
        "OUT":      71,
        "BETA":     0.08,
        "CC":       4,
        "BATCH":    55,
        "LBD":      1.,
        "COMMENT":  "avg from out",
    },
    "FMNISTx":{
        "OUT":      40,
        "BETA":     0.25,
        "CC":       50,
        "BATCH":    160,
        "LBD":      1.,
        "COMMENT":    "best",
    },
    "CIFAR10":{
        "OUT":      90,
        "BETA":     0.4,
        "CC":       6,
        "BATCH":    65,
        "LBD":      1.,
        "COMMENT":    "avg from out",
    },
    "CIFAR10x":{
        "OUT":      60,
        "BETA":     0.05,
        "CC":       5.,
        "BATCH":    32,
        "LBD":      1.,
        "COMMENT":    "best",
    },
    "USPS":{
        "OUT":      40,
        "BETA":     .3,
        "CC":       15,
        "BATCH":    200,
        "LBD":      1.,
        "COMMENT":    "avg from batch",
    },
    "USPSx":{
        "OUT":      45,
        "BETA":     .1,
        "CC":       8,
        "BATCH":    150,
        "LBD":      1.,
        "COMMENT":    "best",
    },
}

CvNET_UNIFx = {
    "MNISTa":{
        "OUT":      22,
        "BETA":     0.04,
        "CC":       16,
        "BATCH":    130,
        "LBD":      1.,
        "COMMENT":    "o22",
    },
    "MNISTb":{
        "OUT":      40,
        "BETA":     .05,
        "CC":       17,
        "BATCH":    180,
        "LBD":      1.,
        "COMMENT":    "o40",
    },
    "FMNISTa":{
        "OUT":      71,
        "BETA":     0.08,
        "CC":       4,
        "BATCH":    55,
        "LBD":      1.,
        "COMMENT":  "o71",
    },
    "FMNISTb":{
        "OUT":      40,
        "BETA":     0.3,
        "CC":       70,
        "BATCH":    220,
        "LBD":      1.,
        "COMMENT":    "o40",
    },
    "CIFAR10a":{
        "OUT":      60,
        "BETA":     0.2,
        "CC":       6,
        "BATCH":    32,
        "LBD":      1.,
        "COMMENT":    "o60",
    },
    "USPSa":{
        "OUT":      45,
        "BETA":     .1,
        "CC":       8,
        "BATCH":    130,
        "LBD":      1.,
        "COMMENT":    "o45",
    },
    "USPSb":{
        "OUT":      15,
        "BETA":     .04,
        "CC":       10,
        "BATCH":    70,
        "LBD":      1.,
        "COMMENT":    "b70",
    },
    "USPSc":{
        "OUT":      15,
        "BETA":     .025,
        "CC":       9,
        "BATCH":    110,
        "LBD":      1.,
        "COMMENT":    "o15",
    },
    "USPSd":{
        "OUT":      70,
        "BETA":     .02,
        "CC":       27,
        "BATCH":    200,
        "LBD":      1.,
        "COMMENT":    "o70",
    },
    "USPSe":{
        "OUT":      50,
        "BETA":     .17,
        "CC":       15,
        "BATCH":    120,
        "LBD":      1.,
        "COMMENT":    "o50",
    },
}
